
fastlane_require "fastlane-plugin-brew"

desc "Lint and test the library"
lane :test do
  brew(command: "install swiftlint")
  swiftlint
  pod_lib_lint
  spm(command: "generate-xcodeproj")
  xcodebuild(
    scheme: "CellKit-Package",
    skip_profile_detection: true,
    archive: false,
    destination: "generic/platform=iOS"
  )
end
